dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
etherscan:
  apiKey: ${ETHERSCAN_TOKEN}
networks:
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
  rinkeby:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
  polygon-test:
    post: "0xA84246f16829F91d3a36bAaAe112dAc2190414FA"
    user: "0x6a0bb5bb1b06ef846bb0470bbB9dd429cFF2F331"
